---
- name: Add COPR repositories for FusionInventory
  yum_repository:
    name: fusioninventory-agent
    description: Copr repo for fusioninventory-agent owned by trasher
    file: fusioninventory_agent
    baseurl: "{{ baseurl_copr }}"
    gpgcheck: yes
    gpgkey: "{{ gpgkey_copr }}"
    skip_if_unavailable: yes
    enabled: no
    state: present

- name: Install Fusioninventory
  yum:
    name: "{{ packages }}"
    enablerepo: "fusioninventory-agent,epel"
    state: latest
  vars:
    packages:
      - fusioninventory-agent
      - fusioninventory-agent-task-inventory

- name: Template for agent configuration
  template:
    src: agent.j2
    dest: /etc/fusioninventory/agent.cfg
    owner: root
    group: root
    mode: 0744

- name: Add fusioninventory-agent to Crontab
  cron:
    name: PATH
    env: yes
    value: /usr/sbin:/usr/bin:/sbin:/bin
    weekday: 0-5
    minute: 55
    hour: 23
    user: root
    job: "/usr/bin/fusioninventory-agent --wait=300"
    cron_file: /etc/crontab
