---
- name: Add COPR repositories for FusionInventory
  yum_repository:
    name: trasher-fusioninventory-agent
    description: Copr repo for fusioninventory-agent owned by trasher
    file: fusioninventory_agent
    baseurl: "{{ baseurl_copr }}"
    gpgcheck: yes
    gpgkey: "{{ gpgkey_copr }}"
    skip_if_unavailable: yes
    enabled: no
    state: present

- name: Install Fusioninventory
  yum:
    name: "{{ packages }}"
    enablerepo: "fusioninventory_agent,epel"
    state: latest
  vars:
    packages:
      - fusioninventory-agent
      - fusioninventory-agent-task-inventory

- name: Template for agent configuration
  template:
    src: agent.j2
    dest: /etc/fusioninventory/agent.cfg
    owner: root
    group: root
    mode: 0744

- name: Add Fusioninventory to cron
  cron:
    name: Fusioninventory Agent
    weekday: 5
    minute: 0
    hour: "{{ 23 | random(seed=inventory_hostname) }}"
    user: root
    job: "/usr/bin/fusioninventory-agent"
    cron_file: fusioninventory